openapi: "3.0.0"
info:
  title: POSTS APIS
  version: 2.0.0
paths:
  /posts:
    get:
      operationId: getPosts
      summary: List Posts
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              examples:
                foo:
                  value:
                    {
                      "posts":
                        [
                          {
                            "id": 1,
                            "title": "Post 1",
                            "author":"pedrinho"
                          },
                          {
                            "id": 2,
                            "title": "Post 2",
                            "author":"padilha"
                          },
                        ],
                    }
        "300":
          description: |-
            300 response
          content:
            application/json:
              examples:
                foo:
                  value: |
                    {
                     "posts":
                        [
                          {
                            "id": 1,
                            "title": "Post 1",
                            "author":"pedrinho"
                          },
                          {
                            "id": 2,
                            "title": "Post 2",
                            "author":"padilha"
                          },
                        ],
                    }
    post:
        operationId: editPosts
        summary: Update Posts
        responses:
          "200":
            description: |-
              200 response
            content:
              application/json:
                examples:
                  foo:
                    value:
                      {
                        "posts":
                          [
                            {
                              "id": 1,
                              "title": "Post 1",
                              "author":"pedrinho"
                            }
                          ],
                      }
       